### ISSUE TITLE
each_limit skipping promises and failing with "Invoking the wait callback did not resolve the promise"

### ISSUE THREAD

**Issue by kicken** [guzzle/promises#133]
**PHP version**: 7.4.9

**Description**
I have some code that downloads and processes sequences of pages multiple times.  Multiple instances of these downloads are gathered up and passed to each_limit to process the chains at a limited concurrency.

With 1.3.1 this process works overall.  After upgrading to 1.4.0 the script fails with 

	Fatal error: Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise

The script also appears to skip some of the promises.

**How to reproduce**
I've reproduced the issue with the following example code:

	<?php
	require 'vendor/autoload.php';

	use GuzzleHttp\Promise\Promise;
	use function GuzzleHttp\Promise\each_limit;

	class Downloader {
	    public function download($upper){
		return $this->step1($upper)
		    ->then(function($result){
			return $this->step2($result);
		    })->then(function($result){
			return $this->step3($result);
		    })->then(function($result){
			return $this->step4($result);
		    });
	    }

	    private function step1($upper){
		$upper = $upper & 0xFF00;

		return $promise = new Promise(function() use (&$promise, $upper){
		    $promise->resolve($upper);
		});
	    }

	    private function step2($result){
		$result = $result | 0x02;

		return $promise = new Promise(function() use (&$promise, $result){
		    $promise->resolve($result);
		});
	    }

	    private function step3($result){
		$result = $result | 0x04;

		return $promise = new Promise(function() use (&$promise, $result){
		    $promise->resolve($result);
		});
	    }

	    private function step4($result){
		return $result | 0x08;
	    }
	}

	function generateDownloadPromises(Downloader $dl, $entries){
	    foreach ($entries as $item){
		yield $dl->download($item << 8)->then(function($result){
		    echo 'Received value: ' . $result . PHP_EOL;

		    return $result;
		});
	    }
	}

	$dl = new Downloader();
	$generator = generateDownloadPromises($dl, range(1, 10));
	each_limit($generator, 3, function($result, $key){
	    echo '[' . $key . '] Promise resolved successfully to ' . $result, PHP_EOL;
	}, function($reason, $key){
	    echo '[' . $key . '] Failed to resolve promise', PHP_EOL;
	    var_dump($reason);
	})->wait();

**Results**
Running the above on 1.3.1 yields the output:

	Received value: 270
	[0] Promise resolved successfully to 270
	Received value: 526
	[1] Promise resolved successfully to 526
	Received value: 782
	[2] Promise resolved successfully to 782
	Received value: 1038
	[3] Promise resolved successfully to 1038
	Received value: 1294
	[4] Promise resolved successfully to 1294
	Received value: 1550
	[5] Promise resolved successfully to 1550
	Received value: 1806
	[6] Promise resolved successfully to 1806
	Received value: 2062
	[7] Promise resolved successfully to 2062
	Received value: 2318
	[8] Promise resolved successfully to 2318
	Received value: 2574
	[9] Promise resolved successfully to 2574

While on 1.4.0 it yields:

	Received value: 270
	[0] Promise resolved successfully to 270
	Received value: 1038
	[3] Promise resolved successfully to 1038
	Received value: 1294
	[4] Promise resolved successfully to 1294
	Received value: 1550
	[5] Promise resolved successfully to 1550
	Received value: 1806
	[6] Promise resolved successfully to 1806
	Received value: 2062
	[7] Promise resolved successfully to 2062
	Received value: 2318
	[8] Promise resolved successfully to 2318
	Received value: 2574
	[9] Promise resolved successfully to 2574
	PHP Fatal error:  Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in G:\xxx\vendor\guzzlehttp\promises\src\Create.php:62
	Stack trace:
	#0 G:\xxx\vendor\guzzlehttp\promises\src\Promise.php(72): GuzzleHttp\Promise\Create::exceptionFor('Invoking the wa...')
	#1 G:\xxx\each_bug.php(66): GuzzleHttp\Promise\Promise->wait()
	#2 {main}
	  thrown in G:\xxx\vendor\guzzlehttp\promises\src\Create.php on line 62

**Additional context**

Aside from the unexpected exception in 1.4.0, you can see that the indexes [1] and [2] are missing, those promises are skipped and never processed.

Looking through and testing various previous commits it appears this issue was introduced by commit 27c7a89.  The code works when using the prior commit 956c5d1

**Comment by GrahamCampbell** [comment]
Your old code only worked because of a bug that was fixed in 1.4.0. You need to return a promise from step4.

**Comment by kicken** [comment]
I considered that might be the case, but determined it is not.   Changing step4 the following does not resolve the issue:

    private function step4($result){
        return Create::promiseFor($result | 0x08);
    }

Requiring a promise return value would seem to be contrary to the documentation and available examples as well.

Having spent time debugging to today I believe the issue is with the end() call introduced in 27c7a89 as it messes up the current/next iteration taking place in the wait function.

**Comment by GrahamCampbell** [comment]
Looks like this was due to https://github.com/guzzle/promises/pull/77. // cc @Tobion @Nyholm @sagikazarmark

**Comment by sschroetke** [comment]
Will there be a Release (1.4.1) with this fix?

**Comment by stickeegreg** [comment]
Please consider releasing this - I just spent a whole day debugging to get to the root of this issue

**Comment by yannickroger** [comment]
Same here, we lost quite some time debuging this.

**Comment by yannickroger** [comment]
@Nyholm maybe if you have a few minutes, that's the only patch since 1.4.0 it should be quick. 🙏

**Comment by Nyholm** [comment]
The thing that would make maintainers more comfortable when releasing a new version is that people test dev-master in their application and confirm that it is working.

**Comment by yannickroger** [comment]
We use the library to run the migration of a big application using a REST API. 

It was broken with 1.4.0, we locked the dependency to 1.3.1 for a couple month, and just gave it another try today. `dev-master` works like a charm to run our migration.
